version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: access_control_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DEBUG=False
    depends_on:
      - db
      - mqtt
    volumes:
      - ./fastapi_access_control:/app
      - ./entrypoint.dev.sh:/app/entrypoint.dev.sh
    entrypoint: ["/app/entrypoint.dev.sh"]
    networks:
      - access_control_network

  db:
    image: postgres:15-alpine
    container_name: access_control_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - access_control_network

  mqtt:
    image: eclipse-mosquitto:2
    container_name: access_control_mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - access_control_network

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:

networks:
  access_control_network:
    driver: bridge 