"""create mqtt_messages table

Revision ID: 8ae6cd1fd7a0
Revises: 
Create Date: 2025-05-24 17:30:53.702309+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae6cd1fd7a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mqtt_messages_id'), 'mqtt_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mqtt_messages_topic'), 'mqtt_messages', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mqtt_messages_topic'), table_name='mqtt_messages')
    op.drop_index(op.f('ix_mqtt_messages_id'), table_name='mqtt_messages')
    op.drop_table('mqtt_messages')
    # ### end Alembic commands ### 